{"uuid": "b8ff1205-473c-4a72-b7f7-6a396f67124b", "children": ["05359be8-e83e-4493-8d7d-9d37eadc3a38", "2e23a73d-80c8-4690-ae12-4db9fce535c2", "7e9d93c7-5845-4b52-9205-b6589d4c53e9", "45e7ad36-7d6d-4e9c-90e9-5890e121fef7", "52db618f-593b-48df-bce7-a69edcf2c032", "c245c53d-3002-4334-a5fd-d0b62631210c", "50e675e0-3fcf-4eef-b6f6-bfd7482abf28", "63cfaa61-d825-43e2-bb9c-5d1ca0ca789c", "d9ebe636-3bf7-4542-87ca-145cf3cdc80e", "d7e5f2cd-5f73-4c85-a80f-ee067ac208c9"], "befores": [{"name": "clear_yaml", "status": "passed", "start": 1652253439853, "stop": 1652253439854}], "afters": [{"name": "clear_yaml::0", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"clear_yaml\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"/Users/xu/PycharmProjects/auto_test/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/xu/PycharmProjects/auto_test/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/xu/PycharmProjects/auto_test/conftest.py\", line 18, in clear_yaml\n    clear_yaml()\n  File \"/Users/xu/PycharmProjects/auto_test/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1166, in result\n    fail(message, pytrace=False)\n  File \"/Users/xu/PycharmProjects/auto_test/venv/lib/python3.8/site-packages/_pytest/outcomes.py\", line 156, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1652253441151, "stop": 1652253441159}], "start": 1652253439853, "stop": 1652253441159}